api:
    host: http://www.lake-district.com
    baseUrl: ${api.host}/api
    search-results:
        page-size: 10

spring:
    h2:
        console:
            enabled: true
    jpa:
        properties:
            hibernate:
                format_sql: true
    jackson:
        serialization:
            INDENT_OUTPUT: true


